#!/bin/sh
clear
echo "  ****************************************************************************"
echo "  **                                                                        **"
echo "  **                   Upload M3U file to the target                        **"
echo "  **                                                                        **"
echo "  **                                                           by Bad Jin   **"
echo "  ****************************************************************************"

path=$(pwd)
ListNo=$1
sourcePath=$path/update/playlist-lilactvHD$1.m3u
targetPath="/opt/lampstack-5.6.24-0/apache2/htdocs/BadJin/Favourites/System"

echo " "
echo "  == Copy all M3U files to the target folder"
cp $sourcePath $targetPath
echo " "
