#!/bin/sh

cd /root/LilacTV
git pull origin master

cd iptv
./iptv-check-all "List1"
sleep 1
./iptv-check-all "List2"
sleep 1
./iptv-check-all "List3"

cd ../
git add .
git commit -m "List Update"
git pull https://badjin:Por96311@github.com/badjin/LilacTV.git master
